spring:
  config:
    import: env.properties
  profiles:
    active: ${ACTIVE}


api:
  version: /api/v1

server:
  port: ${PORT}

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: ${DEV_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: ${DEV_JPA_DIALECT}


---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: ${DEV_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: ${DEV_JPA_DIALECT}

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: ${TEST_DB_DRIVER_CLASS_NAME}
    url: ${TEST_DB_URL}
    username: ${TEST_DB_USER}
    password:
  sql:
    init:
      mode: always
      data-locations: classpath:db/migration/V1_init.sql
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  main:
    allow-circular-references: true
